CREATE TYPE "roles" AS ENUM (
    'usuario',
    'tecnico',
    'administrativo'
);

CREATE TYPE "estadoFactura" AS ENUM (
    'pendiente',
    'pagada',
    'vencida'
);


CREATE TABLE IF NOT EXISTS "Rol" (
    "rol_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "descripcion" roles NOT NULL,
    PRIMARY KEY("rol_id")
);

CREATE TABLE IF NOT EXISTS "Grupos_Mensajeria" (
    "grupo_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "nombre" VARCHAR(255) NOT NULL,
    "fechaCreacion" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY("grupo_id")
);


CREATE TABLE IF NOT EXISTS "Metodos_Pago" (
    "metodo_pago_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "nombre" VARCHAR(255) NOT NULL,
    "isActive" BOOLEAN DEFAULT TRUE,
    PRIMARY KEY("metodo_pago_id")
);


CREATE TABLE IF NOT EXISTS "Usuario" (
    "usuario_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "nombre" VARCHAR(255) NOT NULL,
    "mail" VARCHAR(255) UNIQUE NOT NULL,
    "fechaRegistro" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "rol_id" BIGINT NOT NULL,
    "isActive" BOOLEAN DEFAULT TRUE,
    PRIMARY KEY("usuario_id"),
    FOREIGN KEY("rol_id") REFERENCES "Rol"("rol_id")
        ON UPDATE CASCADE ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS "Usuario_Credencial" (
    "usuario_id" BIGINT NOT NULL UNIQUE,
    "contraseña" VARCHAR(255) NOT NULL,
    PRIMARY KEY("usuario_id"),
    FOREIGN KEY("usuario_id") REFERENCES "Usuario"("usuario_id")
        ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "Sesion" (
    "sesion_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "usuario_id" BIGINT NOT NULL,
    "fechaInicio" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "horaInicio" TIME DEFAULT CURRENT_TIME,
    "fechaCierre" TIMESTAMP,
    "horaCierre" TIME,
    "isActive" BOOLEAN DEFAULT TRUE,
    PRIMARY KEY("sesion_id"),
    FOREIGN KEY("usuario_id") REFERENCES "Usuario"("usuario_id")
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Solicitud_Proceso" (
    "solicitud_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "usuario_id" BIGINT NOT NULL,
    "proceso_id" BIGINT NOT NULL,
    "fechaSolicitud" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "isCompleted" BOOLEAN DEFAULT FALSE,
    "proceso_id" VARCHAR(24),
    PRIMARY KEY("solicitud_id"),
    FOREIGN KEY("usuario_id") REFERENCES "Usuario"("usuario_id")
        ON UPDATE CASCADE ON DELETE RESTRICT,

);

CREATE TABLE IF NOT EXISTS "Facturas" (
    "factura_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "usuario_id" BIGINT NOT NULL,
    "solicitud_id" BIGINT,
    "fechaEmision" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "estadoFactura" estadoFactura DEFAULT 'pendiente',
    PRIMARY KEY("factura_id"),
    FOREIGN KEY("usuario_id") REFERENCES "Usuario"("usuario_id")
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY("solicitud_id") REFERENCES "Solicitud_Proceso"("solicitud_id")
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "Historial_Ejecucion_Procesos" (
    "ejecucion_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "solicitud_id" BIGINT NOT NULL,
    "factura_id" BIGINT,
    "fechaEjecucion" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "resultado" TEXT,
    "isCompleted" BOOLEAN DEFAULT FALSE,
    PRIMARY KEY("ejecucion_id"),
    FOREIGN KEY("solicitud_id") REFERENCES "Solicitud_Proceso"("solicitud_id")
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY("factura_id") REFERENCES "Facturas"("factura_id")
        ON UPDATE CASCADE ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS "Pagos" (
    "pago_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "factura_id" BIGINT NOT NULL,
    "fechaPago" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "montoPagado" DECIMAL(10,2) NOT NULL CHECK ("montoPagado" > 0),
    "metodo_pago_id" BIGINT NOT NULL,
    PRIMARY KEY("pago_id"),
    FOREIGN KEY("factura_id") REFERENCES "Facturas"("factura_id")
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY("metodo_pago_id") REFERENCES "Metodos_Pago"("metodo_pago_id")
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "Cuentas_Corrientes" (
    "cuenta_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "usuario_id" BIGINT NOT NULL UNIQUE,
    "saldoActual" DECIMAL(12,2) DEFAULT 0.00,
    PRIMARY KEY("cuenta_id"),
    FOREIGN KEY("usuario_id") REFERENCES "Usuario"("usuario_id")
        ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "Movimientos_CC" (
    "movimiento_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "cuenta_id" BIGINT NOT NULL,
    "monto" DECIMAL(10,2) NOT NULL,
    "fechaMovimiento" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "referencia_factura_id" BIGINT,
    "referencia_pago_id" BIGINT,
    PRIMARY KEY("movimiento_id"),
    FOREIGN KEY("cuenta_id") REFERENCES "Cuentas_Corrientes"("cuenta_id")
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY("referencia_factura_id") REFERENCES "Facturas"("factura_id")
        ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY("referencia_pago_id") REFERENCES "Pagos"("pago_id")
        ON UPDATE CASCADE ON DELETE SET NULL
);



CREATE TABLE IF NOT EXISTS "Usuarios_Grupo" (
    "usuario_id" BIGINT NOT NULL,
    "grupo_id" BIGINT NOT NULL,
    "fechaUnion" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY("usuario_id", "grupo_id"),
    FOREIGN KEY("usuario_id") REFERENCES "Usuario"("usuario_id")
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY("grupo_id") REFERENCES "Grupos_Mensajeria"("grupo_id")
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Mensaje" (
    "mensaje_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "remitente_id" BIGINT NOT NULL,
    "grupo_id" BIGINT NOT NULL,
    "mensaje" TEXT NOT NULL,
    "fechaEnvio" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY("mensaje_id"),
    FOREIGN KEY("remitente_id") REFERENCES "Usuario"("usuario_id")
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY("grupo_id") REFERENCES "Grupos_Mensajeria"("grupo_id")
        ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE INDEX idx_usuario_mail ON "Usuario"("mail");
CREATE INDEX idx_usuario_rol ON "Usuario"("rol_id");
CREATE INDEX idx_facturas_usuario ON "Facturas"("usuario_id");
CREATE INDEX idx_facturas_estado ON "Facturas"("estadoFactura");
CREATE INDEX idx_pagos_factura ON "Pagos"("factura_id");
CREATE INDEX idx_sesion_usuario ON "Sesion"("usuario_id");
CREATE INDEX idx_mensaje_grupo ON "Mensaje"("grupo_id");
CREATE INDEX idx_movimientos_cuenta ON "Movimientos_CC"("fechaMovimiento");

