CREATE TYPE roles AS ENUM (
    'usuario',
    'tecnico',
    'admin'
);

CREATE TYPE estado_factura AS ENUM (
    'pendiente',
    'pagada',
    'vencida'
);


CREATE TABLE IF NOT EXISTS "Rol" (
    "rol_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "descripcion" roles NOT NULL,
    PRIMARY KEY("rol_id")
);

CREATE TABLE IF NOT EXISTS "Metodos_Pago" (
    "metodo_pago_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "nombre" VARCHAR(255) NOT NULL,
    "isActive" BOOLEAN DEFAULT TRUE,
    PRIMARY KEY("metodo_pago_id")
);



CREATE TABLE IF NOT EXISTS "Usuario" (
    "usuario_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "nombre" VARCHAR(255) NOT NULL,
    "mail" VARCHAR(255) UNIQUE NOT NULL,
    "fechaRegistro" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "rol_id" BIGINT NOT NULL,
    "isActive" BOOLEAN DEFAULT TRUE,
    PRIMARY KEY("usuario_id"),
    -- FK: Depende de "Rol"
    FOREIGN KEY("rol_id") REFERENCES "Rol"("rol_id")
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "Usuario_Credencial" (
    "usuario_id" BIGINT NOT NULL UNIQUE,
    "contraseña" VARCHAR(255) NOT NULL,
    PRIMARY KEY("usuario_id"),
    -- FK: Depende de "Usuario"
    FOREIGN KEY("usuario_id") REFERENCES "Usuario"("usuario_id")
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Cuentas_Corrientes" (
    "cuenta_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "usuario_id" BIGINT NOT NULL UNIQUE,
    "saldoActual" DECIMAL(12,2) DEFAULT 0.00,
    PRIMARY KEY("cuenta_id"),
    -- FK: Depende de "Usuario"
    FOREIGN KEY("usuario_id") REFERENCES "Usuario"("usuario_id")
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Solicitud_Proceso" (
    "solicitud_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "usuario_id" BIGINT NOT NULL,
    "proceso_id" VARCHAR(24),
    "fechaSolicitud" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "isCompleted" BOOLEAN DEFAULT FALSE,
    PRIMARY KEY("solicitud_id"),
    -- FK: Depende de "Usuario"
    FOREIGN KEY("usuario_id") REFERENCES "Usuario"("usuario_id")
        ON UPDATE CASCADE ON DELETE RESTRICT
);



CREATE TABLE IF NOT EXISTS "Facturas" (
    "factura_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "usuario_id" BIGINT NOT NULL,
    "solicitud_id" BIGINT,
    "fechaEmision" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "estadoFactura" estado_factura DEFAULT 'pendiente',
    PRIMARY KEY("factura_id"),
    -- FKs: Depende de "Usuario" y "Solicitud_Proceso"
    FOREIGN KEY("usuario_id") REFERENCES "Usuario"("usuario_id")
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY("solicitud_id") REFERENCES "Solicitud_Proceso"("solicitud_id")
        ON UPDATE CASCADE ON DELETE SET NULL
);



CREATE TABLE IF NOT EXISTS "Pagos" (
    "pago_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "factura_id" BIGINT NOT NULL,
    "fechaPago" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "montoPagado" DECIMAL(10,2) NOT NULL CHECK ("montoPagado" > 0),
    "metodo_pago_id" BIGINT NOT NULL,
    PRIMARY KEY("pago_id"),
    -- FKs: Depende de "Facturas" y "Metodos_Pago"
    FOREIGN KEY("factura_id") REFERENCES "Facturas"("factura_id")
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY("metodo_pago_id") REFERENCES "Metodos_Pago"("metodo_pago_id")
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "Historial_Ejecucion_Procesos" (
    "ejecucion_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "solicitud_id" BIGINT NOT NULL,
    "factura_id" BIGINT,
    "fechaEjecucion" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "resultado" TEXT,
    "isCompleted" BOOLEAN DEFAULT FALSE,
    PRIMARY KEY("ejecucion_id"),
    -- FKs: Depende de "Solicitud_Proceso" y "Facturas"
    FOREIGN KEY("solicitud_id") REFERENCES "Solicitud_Proceso"("solicitud_id")
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY("factura_id") REFERENCES "Facturas"("factura_id")
        ON UPDATE CASCADE ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS "Movimientos_CC" (
    "movimiento_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "cuenta_id" BIGINT NOT NULL,
    "monto" DECIMAL(10,2) NOT NULL,
    "fechaMovimiento" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "referencia_factura_id" BIGINT,
    "referencia_pago_id" BIGINT,
    PRIMARY KEY("movimiento_id"),
    -- FKs: Depende de "Cuentas_Corrientes", "Facturas" y "Pagos"
    FOREIGN KEY("cuenta_id") REFERENCES "Cuentas_Corrientes"("cuenta_id")
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY("referencia_factura_id") REFERENCES "Facturas"("factura_id")
        ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY("referencia_pago_id") REFERENCES "Pagos"("pago_id")
        ON UPDATE CASCADE ON DELETE SET NULL

);


CREATE INDEX idx_usuario_mail ON "Usuario"("mail");
CREATE INDEX idx_usuario_rol ON "Usuario"("rol_id");
CREATE INDEX idx_facturas_usuario ON "Facturas"("usuario_id");
CREATE INDEX idx_facturas_estado ON "Facturas"("estadoFactura");
CREATE INDEX idx_pagos_factura ON "Pagos"("factura_id");
CREATE INDEX idx_movimientos_cuenta ON "Movimientos_CC"("fechaMovimiento");